stages:
    - build_node
    - build_docker

.build_node: &build_node
    stage: build_node
    image: node:12
    services:
        - node:12
    tags:
        - build
        - node
        - docker
    script:
        - npm i
        - npm run build

front-build:
    <<: *build_node
    before_script:
        - cd frontend-docker
    artifacts:
        paths:
            - ./frontend-docker/build/
        expire_in: 1 hour

back-build:
    <<: *build_node
    before_script:
        - cd backend-docker
    artifacts:
        paths:
            - ./backend-docker/package.json
            - ./backend-docker/build/index.js
        expire_in: 1 hour
    
docker_build:
    stage: build_docker
    tags:
        - build
        - shell
    dependencies:
        - front-build
        - back-build
    script:
        - docker-compose build